
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon Feb 10 14:38:20 CST 2014
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int PLUSPLUS = 26; // ++ DONE
  public static final int DIVIDE = 31; // / DONE
  public static final int EQUALS = 35; // == DONE
  public static final int GREATER = 38; // > DONE
  public static final int LPAREN = 19; // ( DONE
  public static final int INT = 3; // int DONE
  public static final int LESS = 37; // < DONE
  public static final int MINUS = 29; // - DONE
  public static final int WRITE = 24; // << DONE
  public static final int RPAREN = 20; // ) DONE
  public static final int NOT = 32; // ! DONE
  public static final int SEMICOLON = 21; // ; DONE
  public static final int AND = 33; // && DONE
  public static final int OR = 34; // || DONE
  public static final int BOOL = 2; // bool DONE
  public static final int COMMA = 22; // , DONE
  public static final int PLUS = 28; // + DONE
  public static final int ASSIGN = 41; // = DONE
  public static final int LESSEQ = 39; // <= DONE
  public static final int IF = 10; // if DONE
  public static final int DOT = 23; // . DONE
  public static final int ID = 14; // 
  public static final int EOF = 0; // 
  public static final int MINUSMINUS = 27; // -- DONE
  public static final int RETURN = 13; // \n
  public static final int TRUE = 5; // true DONE
  public static final int LCURLY = 17; // { DONE
  public static final int CIN = 8; // cin DONE
  public static final int VOID = 4; // void DONE
  public static final int RCURLY = 18; // } DONE
  public static final int INTLITERAL = 15; // integer DONE - what if size if bigger than long
  public static final int TIMES = 30; // * DONE
  public static final int ELSE = 11; // else DONE
  public static final int COUT = 9; // cout DONE
  public static final int READ = 25; // >> DONE
  public static final int NOTEQUALS = 36; // != DONE
  public static final int WHILE = 12; // while DONE
  public static final int GREATEREQ = 40; // >= DONE
  public static final int STRINGLITERAL = 16; // string
  public static final int FALSE = 6; // false DONE
  public static final int STRUCT = 7; // struct DONE
}

